services:
  mysql:
    image: mysql:latest
    container_name: weather-data-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weather_db
    ports:
      - '3306:3306'
    volumes:
      - weather-data:/var/lib/mysql

volumes:
  weather-data:
