services:
  postgres:
    image: postgres:latest
    container_name: weather-data-postgres-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: weather_db
    ports:
      - '5432:5432'
    volumes:
      - weather-data:/var/lib/postgresql/data

volumes:
  weather-data:
